version: '3.8'
services:
  app-control:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    container_name: app-control
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/db_teste_vendas
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      KAFKA_SERVER: kafka:9092
    restart: unless-stopped